#########################
# General Configuration #
#########################

# Config version: This defines the version of your configuration.
version: 1.4

# The directory that backups are saved to.
# 'root' will save backups in the root of the server, 'plugin' will save backups to the plugins data folder.
# 'custom' will use the backup_path file path provided below and place the backups folder inside.
backup_location: plugin

# If backup location is 'custom', choose the absolute path here.
# Windows folder example: C:\Users\YourUsername\Documents.
# Linux and macOS folder example: /Users/YourUsername/Documents.
backup_path: ''

# The worlds chosen to back up: These are the world folder names that will be backed up.
backup_worlds:
  - world

###############
# Auto Backup #
###############

# Auto-backup enabled or not: This sets whether the automatic backup feature is on or off.
auto_backup: true

# If true, each world is backed up individually at different times, determined by dividing the total worlds by the backup interval.
# This means if true, when restoring backups from different worlds at the same time, the backup time will not match.
# If false, all worlds will be backed up at the same time based on the backup interval.
async_backup: false

# Time in minutes between world backups: This sets the interval at which world backups are performed.
# 360 Minutes is 6 Hours
backup_interval: 360

########################
# Format Configuration #
########################

# This is the tag that will be shown for the plugin.
tag: '&f[&aQuickSave&f]'

# This message is displayed when a player doesn't have the necessary permissions.
perms: '&cNo permission.'

# This message is displayed when a world isn't found in the configuration.
no_world: '&cWorld not Found in Config.'

# Message sent when a backup for the requested world is already running.
already_backup: '&cAlready backing up:'

# Message sent in the console when a backup fails.
failed_backup: '&cFailed to back up:'

# Message sent in the console when a backup is complete.
finished_backup: '&bFinished backing up:'

# This is the message that will be shown when the plugin is reloaded.
reload: '&bReloaded.'

# Message sent when a backup is started.
saving: '&bStarting new backup.'

# Message sent when running the status command and no worlds are being backed up.
no_status: '&bCurrently not backing up any worlds.'

# Message sent when running the status command and world/s are being backed up.
status: '&bCurrently backing up:'

#############################
# Folder Size Configuration #
#############################

# The maximum folder size a world can be backed up in megabytes: This value is per world, not total.
# Set false to have no limit.
size_limit: false
size_limit_max: 3000

###############################
# Backup Amount Configuration #
###############################

# This sets the maximum number of backups a world can have: This value is per world, not total.
# Set false to have no limit.
amount_limit: true
amount_limit_max: 10