version: 1.3.2
name: QuickSave
main: me.rockyhawk.qsBackup.QuickSave
author: RockyHawk
api-version: '1.13'
description: Effortless World Backups. Lightweight and Adjustable.
commands:
   quicksave:
      description: Open a command panel.
      usage: /quicksave <args> [args]
      aliases: [qs]
permissions:
   quicksave.admin.reload:
      default: op
   quicksave.admin.backup:
      default: op
   quicksave.help:
      default: op
   quicksave.version:
      default: true